<?php
/**
 * Created by JetBrains PhpStorm.
 * User: gordon
 * Date: 12.02.13
 * Time: 17:11
 * To change this template use File | Settings | File Templates.
 */
?>
<?php
    $_weather = $this->getWeather();
    $_temp_round = 1;
    $_wind_round = 1;
    $_helper = Mage::helper('weather');
    $_date = $_weather->getDate();
?>
<div class="block block-weather" title="<?php echo $_weather->getWeatherDescription() ?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Weather') ?></span></strong>
    </div>
    <p class="block-subtitle"><?php echo $_weather->getLocation(); ?></p>
    <div class="block-content">
        <p class="weather" style="background-image:url(<?php echo $this->getSkinUrl($_weather->getWeatherIcon()) ?>)">
            <strong>
                <?php echo round($_weather->getTemperature(), $_temp_round) . ' ' .
                $_helper->__($_weather->getTemperatureUnit()) ?>
            </strong>
            <span>
                <?php echo round($_weather->getWind(), $_wind_round) . ' ' . $_helper->__($_weather->getWindUnit()) ?>
            </span>
            <br/>
            <span>
                <?php echo $_date->get(Zend_Date::DATETIME_SHORT) ?>
            </span>
        </p>
        <?php // you can remove link if you want to, but it would be nice to thank OpenWeatherMap in this way. ?>
        <p class="empty"><a href="http://openweathermap.org/" title="OpenWeatherMap.org" target="_blank">OpenWeatherMap.org</a></p>
    </div>
</div>